<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.3 (Python 3.9.6 on win32)" generated="20210709 11:25:46.114" rpa="false" schemaversion="2">
<suite id="s1" name="First Csv" source="C:\Users\ANUP\OneDrive\Desktop\VSC\TestData\first_csv.robot">
<kw name="User is allowed to Open amazon" type="SETUP">
<kw name="Open Browser" library="SeleniumLibrary">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20210709 11:25:49.791" level="INFO">Opening browser 'firefox' to base url 'None'.</msg>
<msg timestamp="20210709 11:25:49.801" level="INFO">Firefox driver log is always forced to to: C:\Users\ANUP\OneDrive\Desktop\VSC\geckodriver-2.log</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20210709 11:25:49.881" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<status status="PASS" starttime="20210709 11:25:49.881" endtime="20210709 11:25:49.881"/>
</kw>
<msg timestamp="20210709 11:25:50.024" level="FAIL">WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
</msg>
<status status="FAIL" starttime="20210709 11:25:49.790" endtime="20210709 11:25:50.024"/>
</kw>
<status status="FAIL" starttime="20210709 11:25:49.790" endtime="20210709 11:25:50.025"/>
</kw>
<test id="s1-t1" name="Loginwithexcel">
<status status="FAIL" starttime="20210709 11:25:50.025" endtime="20210709 11:25:50.030">Parent suite setup failed:
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
</status>
</test>
<status status="FAIL" starttime="20210709 11:25:46.127" endtime="20210709 11:25:50.038">Suite setup failed:
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="First Csv">First Csv</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210709 11:25:49.575" level="ERROR">Error in file 'C:\Users\ANUP\OneDrive\Desktop\VSC\TestData\first_csv.robot' on line 3: Resource file '..\VSC\demo.robot' does not exist.</msg>
<msg timestamp="20210709 11:25:49.774" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\Users\ANUP\OneDrive\Desktop\VSC\TestData\first_csv.robot", line 0</msg>
<msg timestamp="20210709 11:25:49.775" level="ERROR">In source file:
  File "C:\Users\ANUP\OneDrive\Desktop\VSC\TestData\../Test/te.csv", line 0</msg>
<msg timestamp="20210709 11:25:49.789" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: AttributeError: No "Test Template" keyword found for first test case.</msg>
<msg timestamp="20210709 11:25:50.027" level="ERROR">Calling method '_start_test' of listener 'DataDriver' failed: AttributeError: 'NoneType' object has no attribute 'get'</msg>
</errors>
</robot>
